FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:80

COPY *.sln ./
COPY SettlyApi/SettlyApi.csproj ./SettlyApi/
COPY ISettlyService/ISettlyService.csproj ./ISettlyService/
COPY SettlyModels/SettlyModels.csproj ./SettlyModels/
COPY SettlyService/SettlyService.csproj ./SettlyService/
COPY SettlyDbManager/SettlyDbManager.csproj ./SettlyDbManager/
COPY SettlyApiTests/SettlyApiTests.csproj ./SettlyApiTests/

RUN dotnet restore

COPY . .

RUN dotnet publish SettlyApi/SettlyApi.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 80

ENTRYPOINT ["dotnet", "SettlyApi.dll"]

