using Bogus;
using Microsoft.EntityFrameworkCore;
using SettlyModels;
using SettlyModels.Entities;
using SettlyDbManager.Utils;

namespace SettlyDbManager;

public class DataSeeder
{
    private readonly SettlyDbContext _context;

    public DataSeeder(SettlyDbContext context)
    {
        _context = context;
    }

    public async Task SeedAllAsync()
    {
        // Clear existing data
        await ClearAllDataAsync();

        // Generate data in dependency order
        await SeedIndependentEntitiesAsync();
        await SeedFirstLevelDependentEntitiesAsync();
        await SeedSecondLevelDependentEntitiesAsync();

        Console.WriteLine("Fake data generation completed!");
    }

    /// <summary>
    /// 专门用于重新生成 suburb 和关联数据的方法
    /// </summary>
    public async Task ReseedSuburbsAndRelatedDataAsync()
    {
        Console.WriteLine("Starting suburb data reseeding...");
        
        // Clear existing suburb-related data
        await ClearSuburbRelatedDataAsync();
        
        // Seed suburbs from CSV
        await SeedSuburbsAsync();
        await _context.SaveChangesAsync();
        
        // Generate realistic data for all suburbs
        var realisticGenerator = new RealisticDataGenerator(_context);
        await realisticGenerator.GenerateRealisticDataForAllSuburbsAsync();
        
        Console.WriteLine("Suburb data reseeding completed!");
    }

    private async Task ClearSuburbRelatedDataAsync()
    {
        Console.WriteLine("Clearing suburb-related data...");
        
        // Delete suburb-related data in dependency order
        _context.SettlyAIScores.RemoveRange(_context.SettlyAIScores);
        _context.RiskDevelopments.RemoveRange(_context.RiskDevelopments);
        _context.Livabilities.RemoveRange(_context.Livabilities);
        _context.PopulationSupplies.RemoveRange(_context.PopulationSupplies);
        _context.IncomeEmployments.RemoveRange(_context.IncomeEmployments);
        _context.HousingMarkets.RemoveRange(_context.HousingMarkets);
        _context.Properties.RemoveRange(_context.Properties);
        _context.Suburbs.RemoveRange(_context.Suburbs);
        
        await _context.SaveChangesAsync();
        Console.WriteLine("Suburb-related data cleared");
    }

    public async Task SeedIndependentEntitiesAsync()
    {
        Console.WriteLine("Seeding Users...");
        await SeedUsersAsync();
        await _context.SaveChangesAsync();

        Console.WriteLine("Seeding Suburbs...");
        await SeedSuburbsAsync();
        await _context.SaveChangesAsync();

        Console.WriteLine("Seeding SuperFunds...");
        await SeedSuperFundsAsync();
        await _context.SaveChangesAsync();

        // await SeedPolicyRulesAsync(); // Temporarily disabled

        Console.WriteLine("Independent entities seeded");
    }

    public async Task SeedFirstLevelDependentEntitiesAsync()
    {
        await SeedPropertiesAsync();
        await SeedHousingMarketsAsync();
        // Note: IncomeEmployments, PopulationSupplies, Livabilities, RiskDevelopments, SettlyAIScores
        // are now generated by RealisticDataGenerator in SeedHousingMarketsAsync()
        await SeedSuperProjectionInputsAsync();
        await SeedChatLogsAsync();

        await _context.SaveChangesAsync();
        Console.WriteLine("First level dependent entities seeded");
    }

    public async Task SeedSecondLevelDependentEntitiesAsync()
    {
        // await SeedFavouritesAsync(); Favourites' data from user saved data, not fake data
        await SeedInspectionPlansAsync();
        await SeedLoanCalculationsAsync();
        await SeedSuperProjectionResultsAsync();
        await SeedSuperProjectionInsightsAsync();
        await SeedUserFundSelectionsAsync();

        await _context.SaveChangesAsync();
        Console.WriteLine("Second level dependent entities seeded");
    }

    public async Task ClearAllDataAsync()
    {
        Console.WriteLine("Clearing all existing data...");
        
        // Delete in reverse dependency order
        _context.UserFundSelections.RemoveRange(_context.UserFundSelections);
        _context.SuperProjectionInsights.RemoveRange(_context.SuperProjectionInsights);
        _context.SuperProjectionResults.RemoveRange(_context.SuperProjectionResults);
        _context.LoanCalculations.RemoveRange(_context.LoanCalculations);
        _context.InspectionPlans.RemoveRange(_context.InspectionPlans);
        _context.Favourites.RemoveRange(_context.Favourites);

        _context.ChatLogs.RemoveRange(_context.ChatLogs);
        _context.SuperProjectionInputs.RemoveRange(_context.SuperProjectionInputs);
        _context.SettlyAIScores.RemoveRange(_context.SettlyAIScores);
        _context.RiskDevelopments.RemoveRange(_context.RiskDevelopments);
        _context.Livabilities.RemoveRange(_context.Livabilities);
        _context.PopulationSupplies.RemoveRange(_context.PopulationSupplies);
        _context.IncomeEmployments.RemoveRange(_context.IncomeEmployments);
        _context.HousingMarkets.RemoveRange(_context.HousingMarkets);
        _context.Properties.RemoveRange(_context.Properties);

        _context.PolicyRules.RemoveRange(_context.PolicyRules);
        _context.SuperFunds.RemoveRange(_context.SuperFunds);
        
        // Clear suburb-related data specifically
        Console.WriteLine("Clearing suburb-related data...");
        _context.Suburbs.RemoveRange(_context.Suburbs);
        
        _context.Users.RemoveRange(_context.Users);

        await _context.SaveChangesAsync();
        Console.WriteLine("All existing data cleared successfully");
    }

    // Independent entity seeding methods
    private async Task SeedUsersAsync()
    {
        var userFaker = new Faker<User>()
            .RuleFor(u => u.Name, f => f.Person.FullName)
            .RuleFor(u => u.Email, f => f.Person.Email)
            .RuleFor(u => u.PasswordHash, f => f.Internet.Password(8) + "_hashed")
            .RuleFor(u => u.CreatedAt, f => f.Date.Between(DateTime.UtcNow.AddYears(-2), DateTime.UtcNow).ToUniversalTime());

        var users = userFaker.Generate(50);
        await _context.Users.AddRangeAsync(users);
    }

    private async Task SeedSuburbsAsync()
    {
        Console.WriteLine("Loading Victoria suburbs from CSV file...");
        
        var csvPath = Path.Combine(Directory.GetCurrentDirectory(), "Data/victoria_suburbs_sorted.csv");
        
        if (!File.Exists(csvPath))
        {
            throw new FileNotFoundException($"CSV file not found at: {csvPath}");
        }

        var suburbs = new List<Suburb>();
        var lines = await File.ReadAllLinesAsync(csvPath);
        
        // Skip header line
        for (int i = 1; i < lines.Length; i++)
        {
            var line = lines[i];
            if (string.IsNullOrWhiteSpace(line)) continue;
            
            var parts = line.Split(',');
            if (parts.Length >= 4)
            {
                // CSV format: ID,suburb,state,postcode
                var id = parts[0].Trim();
                var name = parts[1].Trim();
                var state = parts[2].Trim();
                var postcode = parts[3].Trim();
                
                // Remove quotes if present
                name = name.Trim('"');
                state = state.Trim('"');
                postcode = postcode.Trim('"');
                
                suburbs.Add(new Suburb
                {
                    Name = name,
                    State = state,
                    Postcode = postcode
                });
            }
        }
        
        Console.WriteLine($"Loaded {suburbs.Count} Victoria suburbs from CSV");
        await _context.Suburbs.AddRangeAsync(suburbs);
    }

    private async Task SeedSuperFundsAsync()
    {
        var superFundNames = new[]
        {
            "AustralianSuper", "Sunsuper", "REST Super", "HESTA", "Cbus", "UniSuper",
            "Colonial First State", "BT Super", "MLC Super", "QSuper", "VicSuper",
            "Australian Retirement Trust", "Hostplus", "NGS Super", "Aware Super"
        };

        var superFunds = new List<SuperFund>();
        var faker = new Faker();
        foreach (var fundName in superFundNames)
        {
            superFunds.Add(new SuperFund
            {
                Name = fundName,
                Return1Y = faker.Random.Decimal(0.02m, 0.15m),
                Return3Y = faker.Random.Decimal(0.04m, 0.12m),
                Return5Y = faker.Random.Decimal(0.05m, 0.10m),
                Return10Y = faker.Random.Decimal(0.06m, 0.09m),
                Fee = faker.Random.Decimal(0.005m, 0.02m)
            });
        }
        await _context.SuperFunds.AddRangeAsync(superFunds);
    }

    private async Task SeedPolicyRulesAsync()
    {
        var policyTypes = new[] { "FirstHomeBuyer", "StampDutyExemption", "GrantScheme", "TaxIncentive" };
        var states = new[] { "NSW", "VIC", "QLD", "WA", "SA", "TAS", "ACT", "NT" };

        var policyRuleFaker = new Faker<PolicyRule>()
            .RuleFor(pr => pr.SuburbId, f => f.Random.Bool(0.3f) ? (int?)null : f.Random.Int(1, 100))
            .RuleFor(pr => pr.State, f => f.PickRandom(states))
            .RuleFor(pr => pr.RuleType, f => f.PickRandom(policyTypes))
            .RuleFor(pr => pr.Title, f => $"{f.PickRandom(policyTypes)} Policy for {f.PickRandom(states)}")
            .RuleFor(pr => pr.Description, f => f.Lorem.Paragraph(2))
            .RuleFor(pr => pr.Eligibility, f => f.Lorem.Sentence(8, 15))
            .RuleFor(pr => pr.Link, f => f.Internet.Url())
            .RuleFor(pr => pr.EffectiveDate, f => f.Date.Between(DateTime.UtcNow.AddYears(-3), DateTime.UtcNow.AddYears(1)));

        var policyRules = policyRuleFaker.Generate(30);
        await _context.PolicyRules.AddRangeAsync(policyRules);
    }

    // First level dependent entity seeding methods
    private async Task SeedPropertiesAsync()
    {
        var suburbIds = await _context.Suburbs.Select(s => s.Id).ToListAsync();
        var propertyTypes = new[] { "House", "Apartment", "Townhouse", "Unit", "Villa" };
        var features = new[] { "Pool", "Garage", "Garden", "Balcony", "Air Conditioning", "Parking", "Modern Kitchen" };
        var iamges = new[] { "https://cdn.pixabay.com/photo/2020/04/28/04/03/villa-5102551_1280.jpg", "https://cdn.pixabay.com/photo/2020/04/28/04/03/villa-5102547_1280.jpg", "https://cdn.pixabay.com/photo/2017/04/10/22/28/residence-2219972_1280.jpg" };
        var propertyFaker = new Faker<Property>()
            .RuleFor(p => p.SuburbId, f => f.PickRandom(suburbIds))
            .RuleFor(p => p.Address, f => f.Address.StreetAddress())
            .RuleFor(p => p.PropertyType, f => f.PickRandom(propertyTypes))
            .RuleFor(p => p.Bedrooms, f => f.Random.Int(1, 5))
            .RuleFor(p => p.Bathrooms, f => f.Random.Int(1, 3))
            .RuleFor(p => p.CarSpaces, f => f.Random.Int(0, 3))
            .RuleFor(p => p.Price, f => f.Random.Int(300000, 2000000))
            .RuleFor(p => p.InternalArea, f => f.Random.Int(50, 400))
            .RuleFor(p => p.LandSize, f => f.Random.Int(100, 1000))
            .RuleFor(p => p.YearBuilt, f => f.Random.Int(1950, 2024))
            .RuleFor(p => p.Features, f => f.PickRandom(features, 3).ToArray())
            .RuleFor(p => p.Summary, (f, p) => $"Discover this stunning {p.Bedrooms}-bedroom {p.PropertyType.ToLower()} located in a vibrant suburb. " +
                $"Featuring {p.Features}, this property offers comfort and convenience for modern living. " +
                $"Built in {p.YearBuilt}, it boasts {p.Bathrooms} bathrooms and {p.CarSpaces} car spaces.")
            .RuleFor(p => p.ImageUrl, f => f.PickRandom(iamges))
            .RuleFor(p => p.InspectionTimeOptions, f =>
            {
                var count = f.Random.Int(0, 5);
                var options = new List<DateTime>();
                for (int i = 0; i < count; i++)
                {
                    options.Add(f.Date.Between(DateTime.UtcNow.AddDays(1), DateTime.UtcNow.AddDays(30)));
                }
                return options;
            });
        var properties = propertyFaker.Generate(500);
        await _context.Properties.AddRangeAsync(properties);
    }

    private async Task SeedHousingMarketsAsync()
    {
        // 使用新的 realistic 数据生成器
        var realisticGenerator = new RealisticDataGenerator(_context);
        await realisticGenerator.GenerateRealisticDataForAllSuburbsAsync();
        
        Console.WriteLine("Generated realistic housing market data for all suburbs");
    }


    private async Task SeedSuperProjectionInputsAsync()
    {
        var userIds = await _context.Users.Select(u => u.Id).ToListAsync();

        var superProjectionInputFaker = new Faker<SuperProjectionInput>()
            .RuleFor(spi => spi.UserId, f => f.PickRandom(userIds))
            .RuleFor(spi => spi.CurrentBalance, f => f.Random.Int(10000, 500000))
            .RuleFor(spi => spi.Salary, f => f.Random.Int(50000, 150000))
            .RuleFor(spi => spi.CurrentAge, f => f.Random.Int(25, 60))
            .RuleFor(spi => spi.RetirementAge, f => f.Random.Int(60, 70))
            .RuleFor(spi => spi.EmployerContributionRate, f => f.Random.Decimal(0.095m, 0.12m))
            .RuleFor(spi => spi.UseFhss, f => f.Random.Bool(0.3f))
            .RuleFor(spi => spi.CreatedAt, f => f.Date.Between(DateTime.UtcNow.AddYears(-1), DateTime.UtcNow));

        var superProjectionInputs = superProjectionInputFaker.Generate(75);
        await _context.SuperProjectionInputs.AddRangeAsync(superProjectionInputs);
    }

    private async Task SeedChatLogsAsync()
    {
        var userIds = await _context.Users.Select(u => u.Id).ToListAsync();
        var userMessages = new[]
        {
            "What suburbs should I consider for investment?",
            "How is the market in Melbourne?",
            "Can you analyze this property for me?",
            "What are the best growth areas?",
            "I'm looking for family-friendly suburbs",
            "What's the rental yield in this area?",
            "Are there any upcoming developments?",
            "What's the crime rate like?"
        };
        var aiResponses = new[]
        {
            "Based on current market data, I'd recommend looking at these suburbs...",
            "The Melbourne market is showing strong growth in several key areas...",
            "Let me analyze the property details and market conditions...",
            "Current growth hotspots include areas with strong infrastructure...",
            "For families, consider suburbs with good schools and amenities...",
            "The rental yield in this area is currently around...",
            "There are several major developments planned for this region...",
            "Crime statistics show this area has a relatively low crime rate..."
        };

        var chatLogs = new List<ChatLog>();
        foreach (var userId in userIds.Take(30))
        {
            var conversationLength = new Faker().Random.Int(2, 10);
            for (int i = 0; i < conversationLength; i++)
            {
                // User message
                chatLogs.Add(new ChatLog
                {
                    UserId = userId,
                    Message = new Faker().PickRandom(userMessages),
                    IsUser = true,
                    Timestamp = DateTime.UtcNow.AddDays(-new Faker().Random.Int(1, 30)).AddMinutes(-i * 2)
                });

                // AI response
                chatLogs.Add(new ChatLog
                {
                    UserId = userId,
                    Message = new Faker().PickRandom(aiResponses),
                    IsUser = false,
                    Timestamp = DateTime.UtcNow.AddDays(-new Faker().Random.Int(1, 30)).AddMinutes(-i * 2 + 1)
                });
            }
        }

        await _context.ChatLogs.AddRangeAsync(chatLogs);
    }
    private async Task SeedInspectionPlansAsync()
    {
        var userIds = await _context.Users.Select(u => u.Id).ToListAsync();
        var propertyIds = await _context.Properties.Select(p => p.Id).ToListAsync();
        var inspectionNotes = new[]
        {
            "First inspection - interested in the property",
            "Second viewing with family",
            "Check the condition of the roof and plumbing",
            "Bring building inspector for detailed assessment",
            "Final inspection before making an offer",
            "Compare with other properties in the area",
            "Check neighbourhood and local amenities"
        };

        var inspectionPlans = new List<InspectionPlan>();
        foreach (var userId in userIds.Take(25))
        {
            var inspectionCount = new Faker().Random.Int(1, 4);
            var selectedProperties = new Faker().PickRandom(propertyIds, inspectionCount).ToList();

            foreach (var propertyId in selectedProperties)
            {
                inspectionPlans.Add(new InspectionPlan
                {
                    UserId = userId,
                    PropertyId = propertyId,
                    ScheduledTime = new Faker().Date.Between(DateTime.UtcNow.AddDays(1), DateTime.UtcNow.AddDays(30)),
                    Note = new Faker().PickRandom(inspectionNotes),
                    CreatedAt = new Faker().Date.Between(DateTime.UtcNow.AddDays(-7), DateTime.UtcNow)
                });
            }
        }

        await _context.InspectionPlans.AddRangeAsync(inspectionPlans);
    }

    private async Task SeedLoanCalculationsAsync()
    {
        var userIds = await _context.Users.Select(u => u.Id).ToListAsync();
        var propertyIds = await _context.Properties.Select(p => p.Id).ToListAsync();
        var repaymentTypes = new[] { "Principal and Interest", "Interest Only" };

        var loanCalculations = new List<LoanCalculation>();
        foreach (var userId in userIds.Take(30))
        {
            var calculationCount = new Faker().Random.Int(1, 3);
            var selectedProperties = new Faker().PickRandom(propertyIds, calculationCount).ToList();

            foreach (var propertyId in selectedProperties)
            {
                var faker = new Faker();
                var depositAmount = faker.Random.Int(50000, 400000);
                var loanAmount = faker.Random.Int(300000, 1200000);
                var interestRate = faker.Random.Decimal(0.03m, 0.07m);
                var income = faker.Random.Int(60000, 180000);
                var monthlyRepayment = faker.Random.Int(1500, 6000);
                var totalInterest = faker.Random.Int(200000, 800000);

                loanCalculations.Add(new LoanCalculation
                {
                    UserId = userId,
                    PropertyId = propertyId,
                    DepositAmount = depositAmount,
                    LoanAmount = loanAmount,
                    InterestRate = interestRate,
                    LoanTermYears = faker.Random.Int(20, 30),
                    RepaymentType = faker.PickRandom(repaymentTypes),
                    Income = income,
                    MonthlyRepayment = monthlyRepayment,
                    TotalInterest = totalInterest,
                    TotalCost = loanAmount + totalInterest,
                    RepaymentToIncomeRatio = (decimal)monthlyRepayment * 12 / income,
                    StampDuty = faker.Random.Int(15000, 60000),
                    LegalFees = faker.Random.Int(1000, 3000),
                    InspectionFees = faker.Random.Int(400, 800),
                    ApplicationFee = faker.Random.Int(200, 600),
                    OtherUpfrontCosts = faker.Random.Int(2000, 8000),
                    StressInterestRate = interestRate + 0.03m,
                    StressMonthlyRepayment = (int)(monthlyRepayment * 1.3),
                    StressResultNote = faker.Random.Bool(0.7f) ? "Passes stress test" : "Marginal under stress conditions",
                    FixedMonthly = monthlyRepayment,
                    VariableMonthly = (int)(monthlyRepayment * faker.Random.Decimal(0.95m, 1.05m)),
                    DifferenceNote = faker.Lorem.Sentence(6, 10),
                    CreatedAt = faker.Date.Between(DateTime.UtcNow.AddMonths(-3), DateTime.UtcNow)
                });
            }
        }

        await _context.LoanCalculations.AddRangeAsync(loanCalculations);
    }

    private async Task SeedSuperProjectionResultsAsync()
    {
        var inputIds = await _context.SuperProjectionInputs.Select(spi => spi.Id).ToListAsync();

        var superProjectionResults = new List<SuperProjectionResult>();
        foreach (var inputId in inputIds)
        {
            var faker = new Faker();
            var projectedBalance = faker.Random.Int(500000, 2000000);
            var fhssAmount = faker.Random.Int(30000, 50000);

            superProjectionResults.Add(new SuperProjectionResult
            {
                InputId = inputId,
                ProjectedBalanceAtRetirement = projectedBalance,
                BalanceWithFhss = projectedBalance - fhssAmount,
                BalanceWithoutFhss = projectedBalance,
                NetDifference = fhssAmount,
                FhssWithdrawableAmount = fhssAmount
            });
        }

        await _context.SuperProjectionResults.AddRangeAsync(superProjectionResults);
    }

    private async Task SeedSuperProjectionInsightsAsync()
    {
        var inputIds = await _context.SuperProjectionInputs.Select(spi => spi.Id).ToListAsync();

        var summaryTemplates = new[]
        {
            "Your superannuation is projected to grow significantly over the next {0} years.",
            "Based on current contributions and market performance, your retirement savings are on track.",
            "Your super balance shows strong growth potential with current contribution rates.",
            "The projection indicates a comfortable retirement income based on current settings."
        };

        var recommendationTemplates = new[]
        {
            "Consider increasing voluntary contributions to maximize tax benefits and growth.",
            "Review your investment options to ensure they align with your risk tolerance.",
            "The First Home Super Saver Scheme could help you save for a home deposit.",
            "Consider salary sacrificing to boost your super while reducing taxable income.",
            "Regular reviews of your super performance can help optimize long-term outcomes."
        };

        var superProjectionInsights = new List<SuperProjectionInsight>();
        foreach (var inputId in inputIds)
        {
            var faker = new Faker();
            var yearsToRetirement = faker.Random.Int(10, 40);

            superProjectionInsights.Add(new SuperProjectionInsight
            {
                InputId = inputId,
                SummaryNote = string.Format(faker.PickRandom(summaryTemplates), yearsToRetirement),
                RecommendationNote = faker.PickRandom(recommendationTemplates)
            });
        }

        await _context.SuperProjectionInsights.AddRangeAsync(superProjectionInsights);
    }

    private async Task SeedUserFundSelectionsAsync()
    {
        var userIds = await _context.Users.Select(u => u.Id).ToListAsync();
        var fundIds = await _context.SuperFunds.Select(sf => sf.Id).ToListAsync();
        var inputIds = await _context.SuperProjectionInputs.Select(spi => spi.Id).ToListAsync();

        var userFundSelections = new List<UserFundSelection>();
        foreach (var inputId in inputIds)
        {
            var faker = new Faker();
            var userId = faker.PickRandom(userIds);
            var fundId = faker.PickRandom(fundIds);

            userFundSelections.Add(new UserFundSelection
            {
                UserId = userId,
                InputId = inputId,
                FundId = fundId
            });
        }

        await _context.UserFundSelections.AddRangeAsync(userFundSelections);
    }
}
