name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef          

      - name: Restore dependencies
        run: dotnet restore backend.sln

      - name: Formating Check
        run: dotnet format

      - name: Build
        run: dotnet build backend.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test backend.sln --no-build --configuration Release --logger trx