name: Frontend CICD

on:
  push:
    # branches: 
    # paths:
    #   - 'frontend/**'
  pull_request:
    # paths:
    #   - 'frontend/**'

env:
    AWS_S3_BUCKET: settlyai-frontend-eleanor-practice
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: ap-southeast-2
    SOURCE_DIR: frontend/dist
    CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} 

jobs:
  frontend-cicd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: Start development server
      #   run: pnpm run dev

      - name: Run code linting
        run: pnpm run lint

      - name: Format code
        run: pnpm run format

      # - name: Run Test
      #   run: pnpm run test

      - name: Build Frontend
        run: pnpm exec vite build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"